Sheet: "DATA BASE"

columnList:
- Ma4ds
- Noidungxeploai
- Hovaten
- Ngaysinh
- Thangsinh
- Namsinh
- Cccd
- Ngaycap
- Noiangkykhaisinh
- Quequanthanhnien
- Dantoc
- Tongiao
- Quoctich
- Thuongtrusonha
- Thuongtruap
- Thuongtruxa
- Thuongtrutinhtp
- Tamtrusonha
- Tamtruap
- Tamtruxa
- Tamtrutinhtp
- Thanhphan
- Banthan
- Hocvan
- Trinhochuyenmon
- Chuyennganhaotao
- Nghenghiephiennay
- Noilamviecvahoctap
- Hotencha
- Changaysinh
- Thangsinhcha
- Namsinhcha
- Chasongchet
- Nghenghiepcha
- Hotenme
- Mengaysinh
- Thangsinhme
- Namsinhme
- Mesongchet
- Nghenghiepme
- Hotenvochong
- Ngaysinhvochong
- Thangsinhvochong
- Namsinhvochong
- Nghenghiepcuavochong
- Banthanthanhnienacoconhaychua
- Tongcontronggiainh
- Contrai
- Congai
- Conthumay
- Quequancuacha
- Thuongtruchasonha
- Thuongtruchaap
- Thuongtruchaxa
- Thuongtruchatinhtp
- Tamtruchasonha
- Tamtruchaap
- Tamtruchaxa
- Tamtruchatinhtp
- Cha1tuoien5tuoi
- Cha5tuoientruochethon
- Chasaukethonennay
- Hiennaychalamgitaiau
- Quequancuame
- Thuongtrumesonha
- Thuongtrumeap
- Thuongtrumexa
- Thuongtrumetinhtp
- Tamtrumesonha
- Tamtrumeap
- Tamtrumexa
- Tamtrumetinhtp
- Me1tuoien5tuoi
- Me5tuoientruochethon
- Mesaukethonennay
- Hiennaymelamgitaiau
- Hovatenace
- Ngaythangnamsinhcuaace
- Nghenghiepace
- Vochongace
- C1
- C1phuongxa
- C1tinhtp
- C1namnhaphoc
- C1namtotnghiep
- C2
- C2phuongxa
- C2tinhtp
- C2namnhaphoc
- C2namtotnghiep
- C3
- C3phuongxa
- C3tinhtp
- C3namnhaphoc
- C3namtotnghiep
- 18nay
- Hiennay
- Soienthoaithanhnien
- Soienthoaicha
- Soienthoaime
- Soienthoainguoithankhac


Ma4ds:
  ColumnLabel: "Mã 4DS"
  Question: "Mã 4DS"
  Group: "hiden"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Noidungxeploai:
  ColumnLabel: "Nội dung xếp loại"
  Question: "Nội dung xếp loại"
  Group: "hiden"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Hovaten:
  ColumnLabel: "Họ và tên"
  Question: "Họ và tên"
  Group: "other"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Ngaysinh:
  ColumnLabel: "Ngày sinh"
  Question: "Ngày sinh"
  Group: "date"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Thangsinh:
  ColumnLabel: "Tháng sinh"
  Question: "Tháng sinh"
  Group: "date"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Namsinh:
  ColumnLabel: "Năm sinh"
  Question: "Năm sinh"
  Group: "date"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Cccd:
  ColumnLabel: "CCCD"
  Question: "CCCD"
  Group: "other"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Ngaycap:
  ColumnLabel: "Ngày cấp"
  Question: "Ngày cấp"
  Group: "address"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Noiangkykhaisinh:
  ColumnLabel: "Nơi đăng ký khai sinh"
  Question: "Nơi đăng ký khai sinh"
  Group: "other"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Quequanthanhnien:
  ColumnLabel: "Quê quán thanh niên"
  Question: "Quê quán thanh niên"
  Group: "other"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Dantoc:
  ColumnLabel: "Dân tộc"
  Question: "Dân tộc"
  Group: "other"
  Object: "personal"
  DataType: "DanToc"
  PlaceHolder: ""

Tongiao:
  ColumnLabel: "Tôn giáo"
  Question: "Tôn giáo"
  Group: "other"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Quoctich:
  ColumnLabel: "Quốc tịch"
  Question: "Quốc tịch"
  Group: "other"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Thuongtrusonha:
  ColumnLabel: "Thường trú - số nhà"
  Question: "Thường trú - số nhà"
  Group: "address"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Thuongtruap:
  ColumnLabel: "Thường trú - ấp"
  Question: "Thường trú - ấp"
  Group: "address"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Thuongtruxa:
  ColumnLabel: "Thường trú - xã"
  Question: "Thường trú - xã"
  Group: "address"
  Object: "personal"
  DataType: "Communes"
  PlaceHolder: ""

Thuongtrutinhtp:
  ColumnLabel: "Thường trú - tỉnh/Tp"
  Question: "Thường trú - tỉnh/Tp"
  Group: "address"
  Object: "personal"
  DataType: "Provinces"
  PlaceHolder: ""

Tamtrusonha:
  ColumnLabel: "Tạm trú - số nhà"
  Question: "Tạm trú - số nhà"
  Group: "address"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Tamtruap:
  ColumnLabel: "Tạm trú - ấp"
  Question: "Tạm trú - ấp"
  Group: "address"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Tamtruxa:
  ColumnLabel: "Tạm trú - xã"
  Question: "Tạm trú - xã"
  Group: "address"
  Object: "personal"
  DataType: "Communes"
  PlaceHolder: ""

Tamtrutinhtp:
  ColumnLabel: "Tạm trú - tỉnh/ Tp"
  Question: "Tạm trú - tỉnh/ Tp"
  Group: "other"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Thanhphan:
  ColumnLabel: "Thành phần"
  Question: "Thành phần"
  Group: "other"
  Object: "personal"
  DataType: "ThanhPhan"
  PlaceHolder: ""

Banthan:
  ColumnLabel: "Bản thân"
  Question: "Bản thân"
  Group: "other"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Hocvan:
  ColumnLabel: "Học vấn"
  Question: "Học vấn"
  Group: "education"
  Object: "personal"
  DataType: "HocVan"
  PlaceHolder: ""

Trinhochuyenmon:
  ColumnLabel: "Trình độ chuyên môn"
  Question: "Trình độ chuyên môn"
  Group: "education"
  Object: "personal"
  DataType: "TrinhDoChuyenMon"
  PlaceHolder: ""

Chuyennganhaotao:
  ColumnLabel: "Chuyên ngành đào tạo"
  Question: "Chuyên ngành đào tạo"
  Group: "education"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Nghenghiephiennay:
  ColumnLabel: "Nghề nghiệp hiện nay"
  Question: "Nghề nghiệp hiện nay"
  Group: "other"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Noilamviecvahoctap:
  ColumnLabel: "Nơi làm việc và học tập"
  Question: "Nơi làm việc và học tập"
  Group: "education"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Hotencha:
  ColumnLabel: "Họ tên cha"
  Question: "Họ tên cha"
  Group: "other"
  Object: "father"
  DataType: "string"
  PlaceHolder: ""

Changaysinh:
  ColumnLabel: "Cha - Ngày sinh"
  Question: "Cha - Ngày sinh"
  Group: "date"
  Object: "father"
  DataType: "string"
  PlaceHolder: ""

Thangsinhcha:
  ColumnLabel: "Tháng sinh Cha"
  Question: "Tháng sinh Cha"
  Group: "date"
  Object: "father"
  DataType: "string"
  PlaceHolder: ""

Namsinhcha:
  ColumnLabel: "Năm sinh Cha"
  Question: "Năm sinh Cha"
  Group: "date"
  Object: "father"
  DataType: "string"
  PlaceHolder: ""

Chasongchet:
  ColumnLabel: "Cha Sống/Chết"
  Question: "Cha Sống/Chết"
  Group: "other"
  Object: "father"
  DataType: "SongChet"
  PlaceHolder: ""

Nghenghiepcha:
  ColumnLabel: "Nghề nghiệp cha"
  Question: "Nghề nghiệp cha"
  Group: "other"
  Object: "father"
  DataType: "string"
  PlaceHolder: ""

Hotenme:
  ColumnLabel: "Họ tên mẹ"
  Question: "Họ tên mẹ"
  Group: "other"
  Object: "mother"
  DataType: "string"
  PlaceHolder: ""

Mengaysinh:
  ColumnLabel: "Mẹ - ngày sinh"
  Question: "Mẹ - ngày sinh"
  Group: "date"
  Object: "mother"
  DataType: "string"
  PlaceHolder: ""

Thangsinhme:
  ColumnLabel: "Tháng sinh Mẹ"
  Question: "Tháng sinh Mẹ"
  Group: "date"
  Object: "mother"
  DataType: "string"
  PlaceHolder: ""

Namsinhme:
  ColumnLabel: "Năm sinh Mẹ"
  Question: "Năm sinh Mẹ"
  Group: "date"
  Object: "mother"
  DataType: "string"
  PlaceHolder: ""

Mesongchet:
  ColumnLabel: "Mẹ Sống/Chết"
  Question: "Mẹ Sống/Chết"
  Group: "other"
  Object: "mother"
  DataType: "SongChet"
  PlaceHolder: ""

Nghenghiepme:
  ColumnLabel: "Nghề nghiệp mẹ"
  Question: "Nghề nghiệp mẹ"
  Group: "other"
  Object: "mother"
  DataType: "string"
  PlaceHolder: ""

Hotenvochong:
  ColumnLabel: "Họ tên vợ ( chồng )"
  Question: "Họ tên vợ ( chồng )"
  Group: "other"
  Object: "wife"
  DataType: "string"
  PlaceHolder: ""

Ngaysinhvochong:
  ColumnLabel: "Ngày sinh - vợ chồng"
  Question: "Ngày sinh - vợ chồng"
  Group: "date"
  Object: "wife"
  DataType: "string"
  PlaceHolder: ""

Thangsinhvochong:
  ColumnLabel: "Tháng sinh - vợ chồng"
  Question: "Tháng sinh - vợ chồng"
  Group: "date"
  Object: "wife"
  DataType: "string"
  PlaceHolder: ""

Namsinhvochong:
  ColumnLabel: "Năm sinh vợ chồng"
  Question: "Năm sinh vợ chồng"
  Group: "date"
  Object: "wife"
  DataType: "string"
  PlaceHolder: ""

Nghenghiepcuavochong:
  ColumnLabel: "Nghề nghiệp của - vợ chồng"
  Question: "Nghề nghiệp của - vợ chồng"
  Group: "other"
  Object: "wife"
  DataType: "string"
  PlaceHolder: ""

Banthanthanhnienacoconhaychua:
  ColumnLabel: "Bản thân thanh niên đã có con hay chưa"
  Question: "Bản thân thanh niên đã có con hay chưa"
  Group: "other"
  Object: "personal"
  DataType: "CoKhong"
  PlaceHolder: ""

Tongcontronggiainh:
  ColumnLabel: "Tổng con trong gia đình"
  Question: "Tổng con trong gia đình"
  Group: "other"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Contrai:
  ColumnLabel: "con trai"
  Question: "con trai"
  Group: "other"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Congai:
  ColumnLabel: "con \ngái"
  Question: "con \ngái"
  Group: "other"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Conthumay:
  ColumnLabel: "Con thứ mấy"
  Question: "Con thứ mấy"
  Group: "other"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Quequancuacha:
  ColumnLabel: "Quê quán của Cha"
  Question: "Quê quán của Cha"
  Group: "other"
  Object: "father"
  DataType: "string"
  PlaceHolder: ""

Thuongtruchasonha:
  ColumnLabel: "Thường trú Cha - số nhà"
  Question: "Thường trú Cha - số nhà"
  Group: "address"
  Object: "father"
  DataType: "string"
  PlaceHolder: ""

Thuongtruchaap:
  ColumnLabel: "Thường trú Cha - ấp"
  Question: "Thường trú Cha - ấp"
  Group: "address"
  Object: "father"
  DataType: "string"
  PlaceHolder: ""

Thuongtruchaxa:
  ColumnLabel: "Thường trú Cha - xã"
  Question: "Thường trú Cha - xã"
  Group: "address"
  Object: "father"
  DataType: "Communes"
  PlaceHolder: ""

Thuongtruchatinhtp:
  ColumnLabel: "Thường trú Cha - tỉnh/Tp"
  Question: "Thường trú Cha - tỉnh/Tp"
  Group: "address"
  Object: "father"
  DataType: "Provinces"
  PlaceHolder: ""

Tamtruchasonha:
  ColumnLabel: "Tạm trú Cha - số nhà"
  Question: "Tạm trú Cha - số nhà"
  Group: "address"
  Object: "father"
  DataType: "string"
  PlaceHolder: ""

Tamtruchaap:
  ColumnLabel: "Tạm trú Cha - ấp"
  Question: "Tạm trú Cha - ấp"
  Group: "address"
  Object: "father"
  DataType: "string"
  PlaceHolder: ""

Tamtruchaxa:
  ColumnLabel: "Tạm trú Cha -xã"
  Question: "Tạm trú Cha -xã"
  Group: "address"
  Object: "father"
  DataType: "Communes"
  PlaceHolder: ""

Tamtruchatinhtp:
  ColumnLabel: "Tạm trú Cha - tỉnh/Tp"
  Question: "Tạm trú Cha - tỉnh/Tp"
  Group: "address"
  Object: "father"
  DataType: "Provinces"
  PlaceHolder: ""

Cha1tuoien5tuoi:
  ColumnLabel: "Cha - 1 tuổi đến 5 tuổi"
  Question: "Cha - 1 tuổi đến 5 tuổi"
  Group: "other"
  Object: "father"
  DataType: "string"
  PlaceHolder: ""

Cha5tuoientruochethon:
  ColumnLabel: "Cha - 5 tuổi đến trước hết hôn"
  Question: "Cha - 5 tuổi đến trước hết hôn"
  Group: "other"
  Object: "father"
  DataType: "string"
  PlaceHolder: ""

Chasaukethonennay:
  ColumnLabel: "Cha - Sau kết hôn đến nay"
  Question: "Cha - Sau kết hôn đến nay"
  Group: "other"
  Object: "father"
  DataType: "string"
  PlaceHolder: ""

Hiennaychalamgitaiau:
  ColumnLabel: "Hiện nay cha làm gì? Tại đâu?"
  Question: "Hiện nay cha làm gì? Tại đâu?"
  Group: "other"
  Object: "father"
  DataType: "string"
  PlaceHolder: ""

Quequancuame:
  ColumnLabel: "Quê quán của mẹ"
  Question: "Quê quán của mẹ"
  Group: "other"
  Object: "mother"
  DataType: "string"
  PlaceHolder: ""

Thuongtrumesonha:
  ColumnLabel: "Thường trú Mẹ - số nhà"
  Question: "Thường trú Mẹ - số nhà"
  Group: "address"
  Object: "mother"
  DataType: "string"
  PlaceHolder: ""

Thuongtrumeap:
  ColumnLabel: "Thường trú Mẹ - ấp"
  Question: "Thường trú Mẹ - ấp"
  Group: "address"
  Object: "mother"
  DataType: "string"
  PlaceHolder: ""

Thuongtrumexa:
  ColumnLabel: "Thường trú Mẹ - xã"
  Question: "Thường trú Mẹ - xã"
  Group: "address"
  Object: "mother"
  DataType: "Communes"
  PlaceHolder: ""

Thuongtrumetinhtp:
  ColumnLabel: "Thường trú Mẹ - tỉnh/Tp"
  Question: "Thường trú Mẹ - tỉnh/Tp"
  Group: "address"
  Object: "mother"
  DataType: "Provinces"
  PlaceHolder: ""

Tamtrumesonha:
  ColumnLabel: "Tạm trú Mẹ - số nhà"
  Question: "Tạm trú Mẹ - số nhà"
  Group: "address"
  Object: "mother"
  DataType: "string"
  PlaceHolder: ""

Tamtrumeap:
  ColumnLabel: "Tạm trú Mẹ - ấp"
  Question: "Tạm trú Mẹ - ấp"
  Group: "address"
  Object: "mother"
  DataType: "string"
  PlaceHolder: ""

Tamtrumexa:
  ColumnLabel: "Tạm trú Mẹ - xã"
  Question: "Tạm trú Mẹ - xã"
  Group: "address"
  Object: "mother"
  DataType: "Communes"
  PlaceHolder: ""

Tamtrumetinhtp:
  ColumnLabel: "Tạm trú Mẹ - tỉnh/Tp"
  Question: "Tạm trú Mẹ - tỉnh/Tp"
  Group: "address"
  Object: "mother"
  DataType: "Provinces"
  PlaceHolder: ""

Me1tuoien5tuoi:
  ColumnLabel: "Mẹ  - 1 tuổi đến 5 tuổi"
  Question: "Mẹ  - 1 tuổi đến 5 tuổi"
  Group: "other"
  Object: "mother"
  DataType: "string"
  PlaceHolder: ""

Me5tuoientruochethon:
  ColumnLabel: "Mẹ - 5 tuổi đến trước hết hôn"
  Question: "Mẹ - 5 tuổi đến trước hết hôn"
  Group: "other"
  Object: "mother"
  DataType: "string"
  PlaceHolder: ""

Mesaukethonennay:
  ColumnLabel: "Mẹ - Sau kết hôn đến nay"
  Question: "Mẹ - Sau kết hôn đến nay"
  Group: "other"
  Object: "mother"
  DataType: "string"
  PlaceHolder: ""

Hiennaymelamgitaiau:
  ColumnLabel: "Hiện nay mẹ làm gì? Tại đâu?"
  Question: "Hiện nay mẹ làm gì? Tại đâu?"
  Group: "other"
  Object: "mother"
  DataType: "string"
  PlaceHolder: ""

Hovatenace:
  ColumnLabel: "Họ và tên ACE"
  Question: "Họ và tên ACE"
  Group: "other"
  Object: "sibling"
  DataType: "string"
  PlaceHolder: ""

Ngaythangnamsinhcuaace:
  ColumnLabel: "Ngày tháng năm sinh của ace"
  Question: "Ngày tháng năm sinh của ace"
  Group: "date"
  Object: "sibling"
  DataType: "string"
  PlaceHolder: ""

Nghenghiepace:
  ColumnLabel: "Nghề nghiệp ace"
  Question: "Nghề nghiệp ace"
  Group: "other"
  Object: "sibling"
  DataType: "string"
  PlaceHolder: ""

Vochongace:
  ColumnLabel: "Vợ chồng ace"
  Question: "Vợ chồng ace"
  Group: "other"
  Object: "sibling"
  DataType: "string"
  PlaceHolder: ""

C1:
  ColumnLabel: "C1"
  Question: "C1"
  Group: "education"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

C1phuongxa:
  ColumnLabel: "C1 - Phường/Xã"
  Question: "C1 - Phường/Xã"
  Group: "education"
  Object: "personal"
  DataType: "Communes"
  PlaceHolder: ""

C1tinhtp:
  ColumnLabel: "C1 - tỉnh/Tp"
  Question: "C1 - tỉnh/Tp"
  Group: "education"
  Object: "personal"
  DataType: "Provinces"
  PlaceHolder: ""

C1namnhaphoc:
  ColumnLabel: "C1 - Năm nhập học "
  Question: "C1 - Năm nhập học "
  Group: "education"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

C1namtotnghiep:
  ColumnLabel: "C1 - Năm tốt nghiệp"
  Question: "C1 - Năm tốt nghiệp"
  Group: "education"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

C2:
  ColumnLabel: "C2"
  Question: "C2"
  Group: "education"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

C2phuongxa:
  ColumnLabel: "C2 - Phường/Xã"
  Question: "C2 - Phường/Xã"
  Group: "education"
  Object: "personal"
  DataType: "Communes"
  PlaceHolder: ""

C2tinhtp:
  ColumnLabel: "C2 - tỉnh/Tp"
  Question: "C2 - tỉnh/Tp"
  Group: "education"
  Object: "personal"
  DataType: "Provinces"
  PlaceHolder: ""

C2namnhaphoc:
  ColumnLabel: "C2 - Năm nhập học "
  Question: "C2 - Năm nhập học "
  Group: "education"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

C2namtotnghiep:
  ColumnLabel: "C2 - Năm tốt nghiệp"
  Question: "C2 - Năm tốt nghiệp"
  Group: "education"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

C3:
  ColumnLabel: "C3"
  Question: "C3"
  Group: "education"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

C3phuongxa:
  ColumnLabel: "C3 - Phường/Xã"
  Question: "C3 - Phường/Xã"
  Group: "education"
  Object: "personal"
  DataType: "Communes"
  PlaceHolder: ""

C3tinhtp:
  ColumnLabel: "C3 - tỉnh/Tp"
  Question: "C3 - tỉnh/Tp"
  Group: "education"
  Object: "personal"
  DataType: "Provinces"
  PlaceHolder: ""

C3namnhaphoc:
  ColumnLabel: "C3 - Năm nhập học "
  Question: "C3 - Năm nhập học "
  Group: "education"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

C3namtotnghiep:
  ColumnLabel: "C3 - Năm tốt nghiệp"
  Question: "C3 - Năm tốt nghiệp"
  Group: "education"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

18nay:
  ColumnLabel: "18 - nay"
  Question: "18 - nay"
  Group: "other"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Hiennay:
  ColumnLabel: "Hiện nay"
  Question: "Hiện nay"
  Group: "other"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Soienthoaithanhnien:
  ColumnLabel: "Số điện thoại thanh niên"
  Question: "Số điện thoại thanh niên"
  Group: "other"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""

Soienthoaicha:
  ColumnLabel: "Số điện thoại cha"
  Question: "Số điện thoại cha"
  Group: "other"
  Object: "father"
  DataType: "string"
  PlaceHolder: ""

Soienthoaime:
  ColumnLabel: "Số điện thoại mẹ"
  Question: "Số điện thoại mẹ"
  Group: "other"
  Object: "mother"
  DataType: "string"
  PlaceHolder: ""

Soienthoainguoithankhac:
  ColumnLabel: "Số điện thoại người thân khác"
  Question: "Số điện thoại người thân khác"
  Group: "other"
  Object: "personal"
  DataType: "string"
  PlaceHolder: ""
